services:
  # Pi-hole service for network-wide ad blocking
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      - TZ='America/New_York'  # Change to your timezone
      - WEBPASSWORD=${PIHOLE_PASSWORD}  # Change this to a secure password!
      - ServerIP=${SERVER_IP}  # Using actual host IP from .env
      - FTLCONF_dns_listeningMode=all # Needed for running in Docker with Nginx and Pihole
      # Optional DNS settings - uncomment and adjust as needed:
      # - DNSMASQ_USER=${PIHOLE_USER}  # Commented out - causes issues in container
      - DNS1=${DNS_ONE}
      - DNS2=${DNS_TWO}
    ports:
      - "53:53/tcp"  # DNS TCP
      - "53:53/udp"  # DNS UDP
    volumes:
      - './pihole/config/:/etc/pihole/'
      - './pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    networks:
      - homelab
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '256M'
    networks:
      - homelab

  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    ports:
      - "3010:3000"
      - "3011:3001"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    networks:
      - homelab

networks:
  homelab:
    driver: bridge
