name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['arm32', 'arm64']
        include:
          - arch: 'arm32'
            platform: 'linux/arm/v7'
            dockerfile: 'tests/Dockerfile.test'
          - arch: 'arm64'
            platform: 'linux/arm64'
            dockerfile: 'tests/Dockerfile.test.arm64'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch == 'arm32' && 'arm' || 'arm64' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test container
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --load \
            -t homelab-test-${{ matrix.arch }} \
            -f ${{ matrix.dockerfile }} .

      - name: Run tests
        run: |
          docker run --rm \
            --privileged \
            -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
            -e ARCH=${{ matrix.arch }} \
            homelab-test-${{ matrix.arch }}
